repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - 'flake8-coding==1.3.1'
          - 'flake8-copyright==0.2.2'
          - 'flake8-debugger==3.1.0'
          - 'flake8-mypy==17.8.0'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-json
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/marco-c/taskcluster_yml_validator
    rev: v0.0.3
    hooks:
      - id: taskcluster_yml

default_language_version:
  python: python3.7
